language: go

matrix:
  include:
    - go: "1.9.x"
    - go: "1.10.x"
    - go: "1.11.x"
      env:
        - GO111MODULE=on
      install: true

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)